### ISSUE TITLE
"Uncaught Exception" on Blog

### ISSUE THREAD

**Issue by robertbenjamin** [anchorcms/anchor-site#14]
Going to http://blog.anchorcms.com fails to load the page, instead showing a SQL error message:

    SQLSTATE[42S02]: Base table or view not found: 1146 Table 'anchor.anchor_plugins' doesn't exist
    SELECT * FROM `anchor_plugins`
    system/database/connector.php: 87

![screen shot 2015-01-06 at 4 54 31 pm](https://cloud.githubusercontent.com/assets/8145721/5636984/265ff958-95c5-11e4-8ea0-1c816e2029ea.png)

**Comment by vojtasvoboda** [comment]
It's working, you can close it.

**Comment by robertbenjamin** [comment]
Working for me as well now, thanks.
